["debug", "error", "bug", "crash", "exception", "traceback", "stack trace", "doesn't work", "not working", "broken",
 "failed", "failing"],
["test", "exam", "midterm", "final", "quiz", "practice exam", "study guide", "review sheet", "mock exam"],
["grade", "regrade", "points", "rubric", "partial credit", "feedback", "score", "marked wrong"],
["review", "check", "look over", "verify", "confirm", "sanity check", "edge case", "edge cases"],
["concept", "understand", "explain", "confused", "stuck", "clarify", "intuition", "why", "how does"],
["proof", "derive", "derivation", "theorem", "lemma", "induction", "contradiction", "show that"],
["code", "function", "method", "class", "algorithm", "implementation", "syntax", "compile", "runtime"],
["assignment", "homework", "project", "lab", "deliverable", "submission", "deadline"],
["optimize", "performance", "slow", "efficient", "complexity", "big o", "memory", "timeout"],